volumes:
  wasteless-bites-data:
    external: true
services:
  wasteless-bites-api:
    build:
      context: ./wasteless-bites-api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://example_user:secret@db/example
      WAIT_HOSTS: db:5432
      PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./wasteless-bites-api:/app
    depends_on:
      - db
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: example_user
      POSTGRES_DB: example
    ports:
      - "15432:5432"
    volumes:
      - wasteless-bites-data:/var/lib/postgresql/data
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
